release-artifacts:
    needs:
      - build-java-and-linux-amd64
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Download job artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: artifacts/

      - name: Get Release Tags
        run: |
          j_tag="$(sed 's/\\+/\\+java./' <<< ${{ github.ref_name }})" 
          echo "JAVA_TAG=$j_tag" >> "$GITHUB_ENV"
          l_tag="$(sed 's/\\+/\\+linux./' <<< ${{ github.ref_name }})"
          echo "LINUX_TAG=$l_tag" >> "$GITHUB_ENV"

      - name: Delete Existing Tags
        run: |
          git tag -d ${{ env.JAVA_TAG }} || true
          git tag -d ${{ env.LINUX_TAG }} || true
          git push origin :${{ env.JAVA_TAG }} || true
          git push origin :${{ env.LINUX_TAG }} || true

      - name: Publish Java Artifact
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.JAVA_TAG }}
          artifacts: "artifacts/*.jar"
          prerelease: true
          body: "File upload not for users. **Use the Launcher:** https://github.com/rfresh2/ZenithProxy/releases/tag/launcher-v3"

      - name: Publish Linux Artifact
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.LINUX_TAG }}
          artifacts: "artifacts/ZenithProxy.zip"
          prerelease: true
          body: "File upload not for users. **Use the Launcher:** https://github.com/rfresh2/ZenithProxy/releases/tag/launcher-v3"
